Change AddressBook references to ContactList
AY2021S2-CS2103T-W12-2/tp pull request #39
Opened 2021-03-14 03:36 UTC by rajobasu

2021-03-15 09:31 UTC, Shizheng001 commented on src/test/java/seedu/address/testutil/ContactListBuilder.java
> +    public ContactListBuilder(AddressBook addressBook) {
lets change parameters too

2021-03-22 16:52 UTC, nighoggDatatype requested changes
I am finishing my review now since I don't think I can be exhaustive and timely. What I advise is to do a global search for the word address, the word book, the phrase "address book" and "addressbook", all case insensitive searches. I don't think further comments would be helpful

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/testutil/ContactListBuilder.java
>      private AddressBook addressBook;
Class is wrong and variable name is wrong

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/testutil/ContactListBuilder.java
> + *     {@code AddressBook ab = new ContactListBuilder().withCustomer("John", "Doe").build();}
`AddressBook ab` should be `ContactList cl`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/StorageManagerTest.java
>          AddressBook original = getTypicalAddressBook();
`getTypicalAddressBook` should be `getTypicalContactList`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/StorageManagerTest.java
>          storageManager = new StorageManager(addressBookStorage, userPrefsStorage);
`addressBookStorage` should be `contactListStorage`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/JsonContactListStorageTest.java
>      private void saveAddressBook(ReadOnlyAddressBook addressBook, String filePath) {
Method name again

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/JsonContactListStorageTest.java
> +        readBack = jsonContactListStorage.readAddressBook().get(); // file path not specified
`readAddressBook` method is wrong

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/JsonContactListStorageTest.java
>      public void readAndSaveAddressBook_allInOrder_success() throws Exception {
method name is wrong and probably wrong for many test case code

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/model/ModelManagerTest.java
>          AddressBook differentAddressBook = new AddressBook();
variable name `differentAddressBook `

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/JsonSerializableContactList.java
>       * Converts a given {@code ReadOnlyAddressBook} into this class for Jackson use.
comment has reference to `ReadOnlyAddressBook`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/JsonSerializableContactList.java
>  @JsonRootName(value = "addressbook")
`value = "addressbook"` is probably wrong :(

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/JsonContactListStorage.java
> +        JsonUtil.saveJsonFile(new JsonSerializableContactList(addressBook), filePath);
`addressBook` variable name

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/JsonContactListStorage.java
> +public class JsonContactListStorage implements AddressBookStorage {
Class name `AddressBookStorage`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/JsonContactListStorage.java
>   * A class to access AddressBook data stored as a json file on the hard disk.
Comment is unchanged

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/ContactListStorage.java
> +    Optional<ReadOnlyContactList> readAddressBook(Path filePath) throws DataConversionException, IOException;
method name

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/ContactListStorage.java
> +    void saveAddressBook(ReadOnlyContactList addressBook, Path filePath) throws IOException;
variable name

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/ContactListStorage.java
> +    void saveAddressBook(ReadOnlyContactList addressBook, Path filePath) throws IOException;
Also method name

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/MainApp.java
>       * or an empty address book will be used instead if errors occur when reading {@code storage}'s address book.
bad comment

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/MainApp.java
>              addressBookOptional = storage.readAddressBook();
variable name `addressBookOptional` and method name `readAddressBook`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/MainApp.java
>              initialData = addressBookOptional.orElseGet(SampleDataUtil::getSampleAddressBook);
method `getSampleAddressBook`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/testutil/TypicalCustomers.java
> +    public static ContactList getTypicalAddressBook() {
method name

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/testutil/ContactListBuilder.java
> + * A utility class to help with building Addressbook objects.
comment is bad

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/StorageManagerTest.java
> +        JsonContactListStorage addressBookStorage = new JsonContactListStorage(getTempFilePath("ab"));
variable name `addressBookStorage `

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/StorageManagerTest.java
> +        ContactList original = getTypicalAddressBook();
`getTypicalAddressBook`

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/JsonContactListStorageTest.java
>      public void saveAddressBook_nullFilePath_throwsNullPointerException() {
method name

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/storage/JsonContactListStorageTest.java
> +        assertThrows(NullPointerException.class, () -> saveAddressBook(new ContactList(), null));
`saveAddressBook` is bad

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/model/ModelManagerTest.java
>          differentUserPrefs.setAddressBookFilePath(Paths.get("differentFilePath"));
`setAddressBookFilePath` 👎

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/model/ContactListTest.java
>      public void resetData_withValidReadOnlyAddressBook_replacesData() {
method name

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/model/ContactListTest.java
> +        ContactList newData = getTypicalAddressBook();
`getTypicalAddressBook` is a thorn

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/logic/commands/ClearCommandTest.java
>      public void execute_nonEmptyAddressBook_success() {
method name 👎

2021-03-22 16:52 UTC, nighoggDatatype commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +        public void saveAddressBook(ReadOnlyContactList addressBook, Path filePath) throws IOException {
method name and variable name 👎

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/ui/CustomerCard.java
> +     * @see <a href="https://github.com/se-edu/addressbook-level4/issues/336">The issue on ContactList level 4</a>
I think this one and this one alone should be unchanged given that it references an external project

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/StorageManager.java
> +    public void saveAddressBook(ReadOnlyContactList addressBook, Path filePath) throws IOException {
More bad method names and variable names

2021-03-22 16:52 UTC, nighoggDatatype commented on src/main/java/seedu/address/storage/JsonSerializableContactList.java
> +     * Converts this address book into the model's {@code ContactList} object.
comment "Converts this **_address book_** into the model"

2021-04-12 10:25 UTC, closed without merging